### ISSUE TITLE
Is it possible to reduce the file size for a PNG file without actually resizing the image and not reducing the quality significantly ?

### ISSUE THREAD

**Issue by mandeepm91** [adieuadieu/retinal#49]
I am pushing pictures taken by webcam to s3 bucket and want to process those or rather optimize those images so that their file size reduces but there is not much loss of quality and resolution. Is it possible to accomplish the same with this utility ?

**Comment by adieuadieu** [comment]
Hi @mandeepm91 — Hm.. Sharp does have some parameters for controlling the [quality](http://sharp.readthedocs.io/en/stable/api-output/#jpeg) of the output image, and also by default [omits metadata](http://sharp.readthedocs.io/en/stable/api-output/#withmetadata) (e.g. EXIF data) when writing a new image file, but I'm not sure this would cover what you're looking for. 

However, incorporating such a feature into this project makes a lot of sense. Perhaps enabling the use of a tool like [imagemin](https://github.com/imagemin/imagemin) would be useful?

**Comment by mandeepm91** [comment]
Hi @adieuadieu,
For now we switched to JPEGs because that solved the purpose but I think adding this feature might be useful. I can try implementing this in a few days using imagemin. Let me know if I can proceed.

**Comment by adieuadieu** [comment]
@mandeepm91 Yes I'd welcome a PR. I haven't thought too much about how it would be best to implement the imagemin support. Perhaps extending the "outputs" support currently used for calling Sharp functions, but add a special-case "imagemin" item..
