### ISSUE TITLE
Support for transcoding short videos and generating time-lapse from series of stills, thumbnails & gifs

### ISSUE THREAD

**Issue by superandrew213** [adieuadieu/retinal#50]
It's called `sharp-image` but do you have any plans on supporting video too using `ffmpeg`.

**Comment by adieuadieu** [comment]
Hi @superandrew213 yea it's been on my mind. For longer videos, Lambda doesn't work so well due to it's 5 minute execution-time limit. But it could be useful for things like generating GIFs or combining a batch of images together into a time-lapse video. What use case do you have in mind?

**Comment by superandrew213** [comment]
@adieuadieu at the moment my use case is for short videos (1 min). To transcode and generate thumbs and gifs. There is 'https://github.com/binoculars/aws-lambda-ffmpeg' but I think it would be a really nice addition to `serverless-sharp-image`.

For larger files there is AWS Elastic Transcoder, even though it is quite expensive.

**Comment by adieuadieu** [comment]
@superandrew213 I agree. I'd like to support it. It also aligns with some other work I'm doing with `serverless-chrome` and screencasts.

**Comment by superandrew213** [comment]
@adieuadieu awesome! Will you want to keep the name `serverless-sharp-image` or rename to something like 'serverless-media-processor`?

**Comment by adieuadieu** [comment]
@superandrew213 Will probably rename the project at some point. Not sure what, though.

**Comment by superandrew213** [comment]
@adieuadieu not sure if you are still working on this. We could use AWS Fargate to run long processes for video processing. 

https://serverless.com/blog/serverless-application-for-long-running-process-fargate-lambda
