### ISSUE TITLE
Linter errors

### ISSUE THREAD

**Issue by olivierdelomez** [adieuadieu/retinal#58]
Hi,

I installed and configured the project as described in the docs.

When I run npm run deploy, the linter is not happy :(

`/Users/Documents/workspace/serverless-sharp-image/src/image.js
  17:20  error  Unexpected newline after '('   function-paren-newline
  19:5   error  Unexpected newline before ')'  function-paren-newline
  32:21  error  Unexpected newline after '('   function-paren-newline
  57:3   error  Unexpected newline before ')'  function-paren-newline

/Users/Documents/workspace/serverless-sharp-image/src/image.test.js
  66:1  warning  `test.todo()` should be not be used  ava/no-todo-test
  68:1  warning  `test.todo()` should be not be used  ava/no-todo-test

/Users/Documents/workspace/serverless-sharp-image/src/metadata.js
  28:38  error  Unexpected newline after '('   function-paren-newline
  34:7   error  Unexpected newline before ')'  function-paren-newline
  35:5   error  Unexpected newline before ')'  function-paren-newline

/Users/Documents/workspace/serverless-sharp-image/src/metadata.test.js
   4:8   error    'config' is defined but never used                             no-unused-vars
  25:1   error    `test.todo()` should not be passed an implementation function  ava/no-todo-implementation
  25:1   warning  `test.todo()` should be not be used                            ava/no-todo-test
  25:58  error    't' is defined but never used                                  no-unused-vars
  27:1   error    `test.todo()` should not be passed an implementation function  ava/no-todo-implementation
  27:1   warning  `test.todo()` should be not be used                            ava/no-todo-test
  27:60  error    't' is defined but never used                                  no-unused-vars
  29:67  error    't' is defined but never used                                  no-unused-vars

/Users/Documents/workspace/serverless-sharp-image/src/sharp.js
  14:21  error  Unexpected newline after '('   function-paren-newline
  21:3   error  Unexpected newline before ')'  function-paren-newline

/Users/olivier/Documents/workspace/serverless-sharp-image/src/sharp.test.js
  37:20  error  Unexpected newline after '('   function-paren-newline
  47:3   error  Unexpected newline before ')'  function-paren-newline

✖ 21 problems (17 errors, 4 warnings)
  11 errors, 0 warnings potentially fixable with the `--fix` option.`

Did I forgot to configure something ?

**Comment by darcy** [comment]
I had this problem when I was mistakenly running off `npm`. There is a `yarn.lock` file so switching over to use that with `yarn` fixed everything up for me.

**Comment by sheldon-sminq** [comment]
I get the same error with 

```
yarn run deploy

```

**Comment by boccarab** [comment]
Did you find a solution to this issue?
