### ISSUE TITLE
Created a new repo for generating srcSet and Sizes for img tag

### ISSUE THREAD

**Issue by Jaikant** [adieuadieu/retinal#59]
Hey, 
Thanks for the wonderful library. 
In my use case I need to generate multiple images which could be used in the srcSet and Sizes attributes in the img tag. To do this, I had to change the code in a way not totally in sync with the way you have created this repo. 
The repo I created is [here](https://github.com/Jaikant/lambda-image-sharp)

If you so wish, I could send a pull request if this functionality is something you would like to bake into this, to do that you would have to let me know how you would like me to re-structure so it fits into your mental model.

**Comment by mschipperheyn** [comment]
I'm also interested in this. How would you do this if this was default `retinal`?
