### ISSUE TITLE
deploying retinal issues

### ISSUE THREAD

**Issue by mschipperheyn** [adieuadieu/retinal#63]
Hi, I'm trying this out and basing my test on v0.11.0 as indicated by the README.

- `serverless 1.28.0`

So, I created `config.json` and `yarn test` completes successfully.

Now for `serverless deploy -v`

First issue:
```
Serverless Error ---------------------------------------
 
  No matching handler found for 'handler'. Check your service definition.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.2
     Serverless Version:     1.28.0

```

Changed `serverless.yml`
`handler: src/handler.processImage`

```
Serverless: Could not load webpack config '/Users/Shared/java/projects/react/projects/serverless-sharp-image/webpack.config.js'
 
  Type Error ---------------------------------------------
 
  webpack.optimize.OccurenceOrderPlugin is not a constructor
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.2
     Serverless Version:     1.28.0
 
```

Changed `new webpack.optimize.OccurenceOrderPlugin(),` to `new webpack.optimize.OccurrenceOrderPlugin(),`

```
Serverless: Bundling with Webpack...
 
  Webpack Options Validation Error -----------------------
 
  Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value ".webpack/service" is not an absolute path!
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.2
     Serverless Version:     1.28.0
```

Changed `output.path` to `path: webpackDir` and `module.loaders.loader` to `loader: 'babel-loader',`

```
WARNING in DedupePlugin: This plugin was removed from webpack. Remove it from your configuration.

ERROR in Entry module not found: Error: Can't resolve 'babel' in '/Users/Shared/java/projects/react/projects/serverless-sharp-image'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'babel-loader' instead of 'babel',
                 see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
 
  Error --------------------------------------------------
 
  Webpack compilation error, see above
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.11.2
     Serverless Version:     1.28.0
 

```

- Removed Dedupe

Now it basically works! I have na existing bucket and that failed, but that was mentioned in the README.  Personally, I would prefer it to be able to handle existing buckets without requiring changes to 

- Removed s3 and resources section in serverless.yml

Now it deploys successfully. When I look on AWS, I do see a popup saying "src/handler.js" not found.

**Comment by einSelbst** [comment]
Hi @mschipperheyn . I remember I had such issues but my changes were less. My handler is (still?) called `handler.processImage`, so I guess this is the reason why yours is not found. I know I also had it prefixed with 'src' but that didn't work.
Also, because you haven't mentioned it, if you use existing buckets you have to create the triggering event yourself:

> To use the existing asset bucket an event has to be added via the AWS Lambda Console. Configuration -> S3 -> Configure triggers -> Choose the correct bucket -> Add -> Save (on the top of the page)

(from my internal documentation)

Besides that I only did changes to the provider section (region, profile).
btw I'm still on version `1.27.3` of serverless.
One last tip, I just tried to deploy Jaikant's version (https://github.com/Jaikant/lambda-image-sharp) and had all of your issues as long as I used `yarn`. When I switched to `npm` it just worked.
HTH
